# Generated by Django 2.1.3 on 2018-11-26 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_auto_20181126_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='authors',
        ),
        migrations.AddField(
            model_name='categories',
            name='user',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
