# Generated by Django 2.1.3 on 2018-12-04 05:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_categories_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='userprofile',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='product.UserProfileInfo'),
            preserve_default=False,
        ),
    ]
