# Generated by Django 2.1.3 on 2018-12-04 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20181204_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.UserProfileInfo'),
        ),
    ]
