# Generated by Django 2.1.3 on 2018-12-04 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20181204_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='Profileuser',
            new_name='profileuser',
        ),
    ]
